# Generated by Django 4.0.1 on 2022-07-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.TextField(default='', max_length=15),
        ),
    ]
